version: "3.3"
services:
  jboss-keycloak:
    image: jboss/keycloak
    restart: always
    container_name: demo.keycloak
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - PROXY_ADDRESS_FORWARDING=true
      - KEYCLOAK_IMPORT=/tmp/testrealm.json
    volumes:
      - ./env/keycloak/testrealm.json:/tmp/testrealm.json

  redis:
    image: redis:latest
    restart: always
    container_name: demo.redis
    ports:
      - 6379:6379
    volumes:
      - ./docker/redis:/data
