version: "3.3"
services:
  jboss-keycloak:
    image: jboss/keycloak:10.0.2
    restart: always
    container_name: demo.keycloak
    ports:
      - 28080:8080
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - PROXY_ADDRESS_FORWARDING=true
      - DB_VENDOR=mysql
      - DB_ADDR=mysql_host
      - DB_PORT=3306
      - DB_DATABASE=keycloak
      - DB_USER=root
      - DB_PASSWORD=root
    volumes:
      - ./env/keycloak/testrealm.json:/tmp/testrealm.json
    depends_on:
      - db
    links:
      - db
      - db:mysql_host
  db:
    image: mysql:5.7.30
    container_name: demo.local.mysql_host
    hostname: mysql_host
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: keycloak
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./env/mysql/initdb:/docker-entrypoint-initdb.d
    ports:
      - 23306:3306

  redis:
    image: redis:latest
    restart: always
    container_name: demo.redis
    ports:
      - 26379:6379
    # password setting
    command: redis-server --appendonly yes --requirepass MTIxMg==
    volumes:
      - ./docker/redis:/data
